name: voronoi_clock
description: Voronoi digital clock.
version: 0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  collection: ^1.14.11
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  test: ^1.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
